// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	context "context"
	reports "wanderer/features/reports"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Dashboard provides a mock function with given fields: ctx
func (_m *Service) Dashboard(ctx context.Context) (*reports.Report, error) {
	ret := _m.Called(ctx)

	var r0 *reports.Report
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*reports.Report, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *reports.Report); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*reports.Report)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
