// Code generated by mockery v2.37.1. DO NOT EDIT.

package mocks

import (
	reviews "wanderer/features/reviews"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: userId, newReview
func (_m *Repository) Create(userId uint, newReview reviews.Review) error {
	ret := _m.Called(userId, newReview)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, reviews.Review) error); ok {
		r0 = rf(userId, newReview)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
